// Code is generated by um-model, DO NOT EDIT IT.

/*
Package usms include resources of um usms product

See also

  - API: https://docs.ucloud.cn/api/usms-api/index
  - Product: https://www.ucloud.cn/site/product/usms.html

-TODO 待补充
for detail.
*/
package usms
